[pytest]
testpaths = tests
addopts = -v --browser chromium --html=reports/report.html --self-contained-html

markers =
    smoke: important tests that check core application functionality
    regression: full tests that check detailed application functionality